version: 2.1
jobs:
  BUILD:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Build"
          command: "make all D=0 CI=1"
  RUN:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "RUN"
          command: "make install && Sandbox.out"

workflows:
  say-hello-workflow:
    jobs:
      - BUILD
      - RUN
